### ISSUE TITLE
关于添加论文发表日期的建议

### ISSUE THREAD

**Issue by yaleimeng** [YunjinPark/awesome_talking_face_generation#4]
目前是一年里所有论文排列在一起，也不知道按什么排序的。论文多了就感觉杂乱无章。
希望对于有arxiv链接的论文，添加一个发表日期。便于掌握不同论文公开的时间顺序和时间间隔。当然最好直接按日期倒序排列。因为同一年内间隔半年以上的成果，有可能就差距很大了，而后人的研究通常会在文中跟前人的研究进行比较。
本来我也想做个文献整理，不过您已经做得不错了，就不想再另开项目了。

**Comment by YunjinPark** [comment]
我很感激你的建议。
