### ISSUE TITLE
Full body avatars

### ISSUE THREAD

**Issue by johnGettings** [YunjinPark/awesome_talking_face_generation#7]
Hi, do you know of any papers/ repos that describe the methods for creating a high quality full body avatar such as https://www.synthesia.io?

Thanks

**Comment by johnGettings** [comment]
Also, I created a talking head repo last year if you want to add it to your list.
https://github.com/johnGettings/LIHQ

**Comment by YunjinPark** [comment]
@johnGettings

I also think the quality of Synthesia's avatars is impressive. I'm not sure about the specific algorithms they use, but I believe this link (https://www.synthesia.io/research) might be helpful for you.

 I'm also working on creating avatars at (aipark.ai). I hope you can check out our company's avatars as well. 
 
 Lastly, I'll take a look at the paper you mentioned and add it to my list.
